# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Customiseable port
ENV PORT=5000
EXPOSE ${PORT}

# Command to run the application
CMD ["npm", "start"]
